### ISSUE TITLE
Dommage

### ISSUE THREAD

**Issue by HideakiAtsuyo** [GalackQSM/DeltaBot#2]
C'est dommage de ne pas upload les fichiers d'un [bot](https://github.com/Androz2091/AtlantaBot) que tu as juste modifié mais bon

**Comment by GalackQSM** [comment]
non mes tout le monde le sais que ses basé d'atlanta hein

**Comment by HideakiAtsuyo** [comment]
> 
> 
> non mes tout le monde le sais que ses basé d'atlanta hein

Donc soit tu as pas compris soit tu fais exprès, j'ai pas dis ça apprend à lire merci

**Comment by GalackQSM** [comment]
Bah si tu veut la source tien https://github.com/Androz2091/AtlantaBot

**Comment by HideakiAtsuyo** [comment]
C'est dur d'envoyer un message sans l'éditer ;)
